### ISSUE TITLE
`AbstractDynamicObject$CustomMessageMissingMethodException` with Gradle 7.3

### ISSUE THREAD

**Issue by carlosame** [jjohannes/extra-java-module-info#20]
The [Carte Project](https://sourceforge.net/p/carte/carte/ci/master/tree/) uses your plugin to declare several automatic module names, and the current Gradle wrapper (7.2) runs any task flawlessly:
```
$ ./gradlew clean

BUILD SUCCESSFUL in 4s
14 actionable tasks: 14 executed
```
However, if I try to run a task with Gradle 7.3 it fails:
```
$ gradle clean

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\***\carte\carte\build.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'io.sf.carte.java-conventions']
> Failed to apply plugin 'io.sf.carte.java-conventions'.
   > org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method extraJavaModuleInfo() for arguments [precompiled_IoSfCarteJavaConventions$_run_closure5@1c5037b6] on project ':carte' of type org.gradle.api.Project.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
10 actionable tasks: 10 executed
```
The error happens with Java 17 and also with 11 (the project requires Java 11+ to build).

And the stack trace goes down to:
```javastacktrace
Caused by: java.lang.RuntimeException: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method extraJavaModuleInfo() for arguments [precompiled_IoSfCarteJavaConventions$_run_closure5@6d29a2c0] on project ':carte' of type org.gradle.api.Project.
        at IoSfCarteJavaConventionsPlugin.apply(IoSfCarteJavaConventionsPlugin.java:30)
        at IoSfCarteJavaConventionsPlugin.apply(IoSfCarteJavaConventionsPlugin.java:10)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:187)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$100(DefaultPluginManager.java:52)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:282)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:68)
        at org.gradle.api.internal.plugins.DefaultPluginManager.lambda$doApply$0(DefaultPluginManager.java:167)
        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:44)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:166)
        ... 155 more
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method extraJavaModuleInfo() for arguments [precompiled_IoSfCarteJavaConventions$_run_closure5@6d29a2c0] on project ':carte' of type org.gradle.api.Project.
        at org.gradle.internal.metaobject.AbstractDynamicObject$CustomMissingMethodExecutionFailed.<init>(AbstractDynamicObject.java:190)
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:184)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.methodMissingException(BasicScript.java:162)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:167)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
        at precompiled_IoSfCarteJavaConventions.run(precompiled_IoSfCarteJavaConventions:64)
        at IoSfCarteJavaConventionsPlugin.apply(IoSfCarteJavaConventionsPlugin.java:28)
        ... 172 more
```
To reproduce the error, the source code can be easily obtained with `git clone https://git.code.sf.net/p/carte/carte carte`.

Any suggestion?

**Comment by jjohannes** [comment]
@carlosame I am surprised that it ever worked the way it is right now. :) 

You are using the `extraJavaModuleInfo { }` before you apply the plugin. Not sure why it worked in 7.2 but it must be some weird coincidence. What you should ideally do is:

- Apply the plugin inside `io.sf.carte.java-conventions.gradle`

```
plugins {
  id 'java-library'
  id 'maven-publish'
  id 'de.jjohannes.extra-java-module-info'
}
```

- For that you need to add a dependency to the module containing the plugin in `buildSrc/build.gradle`

```
dependencies {
  implementation("de.jjohannes.gradle:extra-java-module-info:0.9")
}
```

You should then remove the plugin from `carte/build.gradle` and you can remove the `pluginManagement { plugins {} }` stuff from `settings.gradle`.

If you want to continue to manage plugin versions in `gradle.properties`, you would need a separate `gradle.properties` in buildSrc.

The README also describes this setup: https://github.com/jjohannes/extra-java-module-info#plugin-dependency

**Comment by carlosame** [comment]
Thank you for your reply.

> You are using the `extraJavaModuleInfo { }` before you apply the plugin. Not sure why it worked in 7.2 but it must be some weird coincidence.

I missed that I was applying the conventions plugin before your plugin. I applied your suggested fix and it is committed now.
